/**
 * Pure catalog-to-types logic shared by the CLI (`scripts/generate-i18n-types.mjs`)
 * and its test (`src/i18n/generate-catalog-types.test.ts`), so the generator and
 * its coverage can never drift apart.
 */

/** Recursively flattens a nested catalog object into dotted, namespaced keys. */
export function flattenCatalogKeys(catalog, namespace) {
  const keys = [];

  function walk(obj, prefix) {
    for (const [key, value] of Object.entries(obj)) {
      const nextPrefix = `${prefix}.${key}`;
      if (value && typeof value === 'object' && !Array.isArray(value)) {
        walk(value, nextPrefix);
      } else {
        keys.push(nextPrefix);
      }
    }
  }

  walk(catalog, namespace);
  return keys.sort();
}

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/generate-i18n-types.mjs — do not edit by hand.\n' +
  '// Regenerate with: pnpm run i18n:generate\n\n';

/** Renders the generated `MESSAGE_KEYS` / `MessageKey` module source for the given keys. */
export function generateKeysFileContent(keys) {
  const lines = keys.map((key) => `  '${key}',`).join('\n');
  return (
    GENERATED_HEADER +
    `export const MESSAGE_KEYS = [\n${lines}\n] as const;\n\n` +
    'export type MessageKey = (typeof MESSAGE_KEYS)[number];\n'
  );
}
